id: ACFAC4833
base_file: fD907.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:27:01.293905
  last_modified_at: 2022-06-17 11:27:01.293911
